services:
  backend:
    build:
      context: .
    ports:
      - 9080:8080
      
    depends_on:
      - db
    
    volumes:
      - ./:/app
    environment:
      - SNMP_HOST=db
      - MQTT_BROKER_URL=test.mosquitto.org  # Ajoutez l'adresse du broker MQTT
      - MQTT_BROKER_PORT=1883  
    
  db:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
